language: rust
cache: cargo

matrix:
  include:
    - os: linux
      rust: nightly

    - os: linux
      rust: stable

    - os: osx
      rust: nightly

    - os: osx
      rust: stable

script:
  - cargo check
  - cargo test -- --test-threads=1

branches:
  only:
    - master

notifications:
  email:
    on_success: never