[package]
authors = ["rchaser53 <tayoshizawa29@gmail.com>"]
name = "hoge-rust"
version = "0.1.0"

[dependencies]
clap = "~2.27.0"
lazy_static = "1.0.1"
regex = "0.2"
reqwest = "0.8.6"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0"
url = "1.7.0"
